routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});
Auth::routes();
Route::get('/register', function () {
    return redirect()->route('login');
});
Route::get('/password/reset', function () {
    return redirect()->route('login');
});
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home/profile', 'HomeController@userIndex')->name('user.profile');
    Route::post('/home/profile/update', 'HomeController@userUpdate')->name('user.profile.update');
    //router crud user
    Route::get('user/listpetugas', 'UserController@user_petugas');
    Route::get('user/listsiswa', 'UserController@user_siswa');
    Route::resource('user', 'UserController');
    //router crud category
    Route::get('category/select', 'CategoryController@selectCategory');
    Route::resource('category', 'CategoryController');
    //router crud book
    Route::resource('book', 'BookController');
    //router crud borrowed book
    Route::get('borrows/bookslist', 'BorrowedBookController@borrowBooksList')->name('borrows.list');
    Route::resource('borrows', 'BorrowedBookController');
    //router crud returned book
    Route::post('returns/verifreturn/{id}', 'ReturnedBookController@verifReturn');
    Route::get('returns/borrows/book', 'ReturnedBookController@borrowedReturnedIndex')->name('returns.borrows.book');
    Route::resource('returns', 'ReturnedBookController');
    //router export excel
    Route::get('export', 'ExportExcelController@indexAllExport')->name('index.export.excel');
    Route::post('export/borrowreturnbook', 'ExportExcelController@allExportBorrowReturnBook')->name('export.excel.borrowreturn');
    //router test
    Route::get('test', 'test@index');
    Route::post('test/store', 'test@store')->name('test.store');
});

app/borrowed_book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class borrowed_book extends Model
{
    //pinjam buku
    protected $table = "borrowed_books";
    protected $primaryKey = "id";
    protected $fillable = ["user_id","book_id","borrow_date"];
    public $timestamps = false;

    public function books()
    {
        return $this->belongsTo(Book::class, "book_id", "id");
    }

    public function users()
    {
        return $this->belongsTo(User::class, "user_id", "id");
    }

    public function returned_book()
    {
        return $this->hasOne(returned_book::class, "borrowed_book_id", "id");
    }
}

app/Http/Controllers/BorrowedBookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\borrowed_book;
use \App\Book;
use \App\Category;
use \App\returned_book;
use Carbon\Carbon;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Gate;

class BorrowedBookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('roleSiswa');
        $categories = Category::orderBy('id', 'ASC')->get();
        $all_book = Book::with('categories')->paginate(4);
        $book = $request->search_book;
        $category = $request->category;
        if ($request->search_book) {
            if ($request->category) {
                $all_book = Book::with('categories')->where('title', 'LIKE', "%$book%")
            ->whereHas('categories', function ($query) use ($category) {
                $query->where('name', 'LIKE', "%$category%");
            })->paginate(4);
            } else {
                $all_book = Book::with('categories')->where('title', 'LIKE', "%$book%")
            ->paginate(4);
            }
        } elseif ($request->category) {
            $all_book = Book::with('categories')->where('title', 'LIKE', "%$book%")
            ->whereHas('categories', function ($query) use ($category) {
                $query->where('name', 'LIKE', "%$category%");
            })->paginate(4);
        }
        return view('borrowed_book.index', compact('categories', 'all_book'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('roleSiswa');
        try {
            $check_book = Book::findOrFail($request->book_id);
            if ($check_book->status == "ada") {
                $borrow = new borrowed_book();
                $borrow->user_id = \Auth::user()->id;
                $borrow->book_id = $request->book_id;
                $borrow->borrow_date = Carbon::now();
                $borrow->save();
                $returned = new returned_book();
                $returned->user_id = \Auth::user()->id;
                $returned->book_id = $request->book_id;
                $returned->borrowed_book_id = $borrow->id;
                $returned->status_return = "pinjam";
                $check_book->status = "pinjam";
                $returned->save();
                $check_book->save();
                return \Response::json(['method' => 'save'], 200);
            } elseif ($check_book->status == "pinjam") {
                return \Response::json('The book has been borrowed', 403);
            } elseif ($check_book->status == "hilang") {
                return \Response::json('The book is gone', 403);
            } elseif ($check_book->status == "rusak") {
                return \Response::json('The book is damaged', 403);
            }
        } catch (\Throwable $th) {
            return \Response::json(404);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->authorize('roleSiswa');
        try {
            $random_book =  Book::where('id', '!=', $id)->inRandomOrder()->limit(4)->get();
            $show_book = Book::findOrFail($id);
            return view('borrowed_book.show', compact('show_book', 'random_book'));
        } catch (\Throwable $th) {
            \abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function borrowBooksList(Request $request)
    {
        $this->authorize('rolePetugas');
        $borrow_book = borrowed_book::with('books')->with('users');
        if ($request->ajax()) {
            return DataTables::of($borrow_book)
            ->addIndexColumn()
            ->addColumn('action', function ($borrow_book) {
            })
            ->rawColumns(['action'])
            ->make(true);
        }
        return \view('borrowed_book.list');
    }
}

resources/views/borrowed_book/index.blade.php
@extends('layouts.global')
@section('title')
Borrowed Book
@endsection
@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection
@section('js')
<script src="{{ asset('js/borrow.js') }}"></script>
@endsection
@section('borrow1')
active
@endsection
@section('borrow2')
show
@endsection
@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="row page-inner py-5">
        <div class="col-md-8">
            <form action="{{ route('borrows.index') }}" method="GET">
                <div class="input-group">
                    <input type="text" class="form-control w-50 form-control-sm" placeholder="Search Book"
                        name="search_book" value="{{ Request::get('search_book') }}">
                    <select class="custom-select w-25" id="inputGroupSelect02" name="category">
                        <option value="" selected>Category</option>
                        @foreach ($categories as $category)
                        <option value="{{ $category->name }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                    <div class="input-group-append">
                        <input type="submit" value="Search" class="btn btn-primary btn-sm">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        @if (Request::get('search_book'))
                        search results for "{{ Request::get('search_book') }}"
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        @foreach ($all_book as $book)
                        <div class="col-lg-3 col-md-4 col-sm-4 col-6 mt-3 card-group">
                            <div class="card shadow rounded">
                                <img src="storage/{{ $book->cover }}" alt="" class="card-img-top" height="240px"
                                    width="180px">
                                <div class="card-body">
                                    <h4 class="card-title text-truncate font-weight-bolder">
                                        {{ $book->title }}
                                    </h4>
                                    <h6 class="card-subtitle text-truncate mt-1">
                                        Category :
                                        @foreach ($book->categories as $category)
                                        {{ $category->name }},
                                        @endforeach
                                    </h6>
                                    <h6 class="card-subtitle text-truncate mt-1">
                                        Status : @if ($book->status == "ada")
                                        <span class="badge badge-success">{{ $book->status }}</span>
                                        @elseif($book->status == "pinjam")
                                        <span class="badge badge-primary">{{ $book->status }}</span>
                                        @elseif($book->status == "rusak")
                                        <span class="badge badge-warning">{{ $book->status }}</span>
                                        @elseif($book->status == "hilang")
                                        <span class="badge badge-danger">{{ $book->status }}</span>
                                        @endif
                                    </h6>
                                </div>
                                <div class="card-footer pt-0 align-self-center text-center">
                                    @if ($book->status == "ada")
                                    <button onclick="borrow_book('{{ $book->id }}')"
                                        class="btn btn-sm btn-rounded btn-outline-primary mt-2 {{ $book->id }}">Select
                                        Book</button>
                                    @endif
                                    <a href="{{ route('borrows.show',[$book->id]) }}"
                                        class="btn btn-sm btn-rounded btn-outline-secondary mt-2">Detail Book</a>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
                <div class="card-footer">
                    {{$all_book->appends(Request::all())->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/borrowed_book/list.blade.php
@extends('layouts.global')
@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/v/bs4/jq-3.3.1/dt-1.10.22/b-1.6.5/r-2.2.6/sc-2.0.3/datatables.min.css" />
@endsection
@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
    var table = $("#tabel_borrow").DataTable({
    responsive: true,
    processing: true,
    serverSide: true,
    order : [[ 4, "desc" ]],
    ajax: "/borrows/bookslist",
    columns: [{
            data: "DT_RowIndex",
            name: "DT_RowIndex",
            searchable: false,
            orderable: false
        },
        {
            data: "users.name",
            name: "users.name"
        },
        {
            data: "books.id",
            name: "books.id"
        },
        {
            data: "books.title",
            name: "books.title"
        },
        {
            data: "borrow_date",
            name: "borrow_date"
        },
        {
            data: "action",
            name: "action",
            orderable: false,
            searchable: false
        }
    ]
});
window.onresize = function() {
    table.columns.adjust().responsive.recalc();
}
</script>
@endsection
@section('title')
    All Borrow Books
@endsection
@section('borrow1')
active
@endsection
@section('borrow2')
show
@endsection
@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 fw-bold">Borrow Book List</h2>
                <h5 class="text-white op-7 mb-2">Read Update Delete Borrow Book List Data</h5>
            </div>
        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-head">
                        <div class="card-title">All Borrow Book List</div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="tabel_borrow" class="display table table-hover nowrap  w-100" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="all">No</th>
                                    <th class="all">User</th>
                                    <th class="all">Book Id</th>
                                    <th>Book</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/borrowed_book/show.blade.php
@extends('layouts.global')
@section('title')
Detail Book {{ $show_book->title }}
@endsection
@section('css')
<meta name="csrf-token" content="{{ csrf_token() }}">
@endsection
@section('js')
<script src="{{ asset('js/borrow.js') }}"></script>
@endsection
@section('borrow1')
active
@endsection
@section('borrow2')
show
@endsection
@section('content')
<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>
                <h2 class="text-white pb-2 ">Detail Book "{{ $show_book->title }}"</h2>
            </div>
        </div>
    </div>
</div>
<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-tools">
                            <a href="#" onclick="window.history.back()"
                                class="btn btn-sm btn-rounded btn-primary">Back</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="img text-center">
                                <img src="/storage/{{ $show_book->cover }}" alt="" class=" img-fluid ">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered border">
                                    <thead>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="font-weight-bold">Title</td>
                                            <td>{{ $show_book->title }}</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Slug</td>
                                            <td>{{ $show_book->slug }}</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Author</td>
                                            <td>{{ $show_book->author }}</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Publisher</td>
                                            <td>{{ $show_book->publisher }}</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Category</td>
                                            <td>@foreach ($show_book->categories as $book)
                                                {{ $book->name }},
                                                @endforeach</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Status Buku</td>
                                            <td>{{ $show_book->status }}</td>
                                        </tr>
                                        <tr>
                                            <td class="font-weight-bold">Synopsis</td>
                                            <td>{{ $show_book->synopsis }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            @if ($show_book->status == "ada")
                            <button onclick="borrow_book('{{ $show_book->id }}')"
                                class="btn btn-sm btn-rounded btn-primary {{ $show_book->id }}">Select
                                Book</button>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Related books
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        @foreach ($random_book as $book)
                        <div class="col-lg-3 col-md-4 col-sm-4 col-6 mt-3 card-group">
                            <div class="card shadow rounded">
                                <img src="{{ asset('storage/'.$book->cover) }}" alt="" class="card-img-top"
                                    height="240px" width="180px">
                                <div class="card-body">
                                    <h4 class="card-title text-truncate font-weight-bolder">
                                        {{ $book->title }}
                                    </h4>
                                    <h6 class="card-subtitle text-truncate mt-1">
                                        Category :
                                        @foreach ($book->categories as $category)
                                        {{ $category->name }},
                                        @endforeach
                                    </h6>
                                    <h6 class="card-subtitle text-truncate mt-1">
                                        Status : @if ($book->status == "ada")
                                        <span class="badge badge-success">{{ $book->status }}</span>
                                        @elseif($book->status == "pinjam")
                                        <span class="badge badge-primary">{{ $book->status }}</span>
                                        @elseif($book->status == "rusak")
                                        <span class="badge badge-warning">{{ $book->status }}</span>
                                        @elseif($book->status == "hilang")
                                        <span class="badge badge-danger">{{ $book->status }}</span>
                                        @endif
                                    </h6>
                                </div>
                                <div class="card-footer pt-0 align-self-center text-center">
                                    @if ($book->status == "ada")
                                    <button onclick="borrow_book('{{ $book->id }}')"
                                        class="btn btn-sm btn-rounded btn-outline-primary mt-2 {{ $book->id }}">Select
                                        Book</button>
                                    @endif
                                    <a href="{{ route('borrows.show',[$book->id]) }}"
                                        class="btn btn-sm btn-rounded btn-outline-secondary mt-2">Detail Book</a>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection